@WebAPI_HostAddress = http://localhost:5035

GET {{WebAPI_HostAddress}}/healthcheck/
Accept: application/json

###

GET {{WebAPI_HostAddress}}/contatos
Accept: application/json

###

POST {{WebAPI_HostAddress}}/contatos
Content-Type: application/json

{
  "nome": "John Doe",
  "email": "johndoe@example.com",
  "codigoArea": "67",
  "telefone": "992638484"
}

###

PUT {{WebAPI_HostAddress}}/contatos/df50bda0-36a2-4171-bd24-7ab105ad5922
Content-Type: application/json

{
  "id": "df50bda0-36a2-4171-bd24-7ab105ad5922",
  "nome": "John Doe",
  "email": "johndoe@example.com",
  "codigoArea": "67",
  "telefone": "992638484"
}

###